version: "3.3"
services:
  spring-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/rental-db?autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Admin@123
    depends_on:
      - mysql-db
  mysql-db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Admin@123
      - MYSQL_DATABASE=rental-db
    ports:
      - 3307:3306
    volumes:
      - mysql_db_data:/var/lib/mysql
volumes:
  mysql_db_data: